/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        display: ['"Bebas Neue"', 'cursive'],
        body:    ['"Rajdhani"', 'sans-serif'],
        mono:    ['"JetBrains Mono"', 'monospace'],
      },
      colors: {
        pitch:   { 300:'#40ffaa', 400:'#00ff88', 500:'#00cc6a' },
        stadium: { 900:'#04080f', 800:'#070f1c', 700:'#0d1a2e', 600:'#122238', 500:'#1a2d47' },
        ember:   { 400:'#ff6b35', 500:'#ff5500' },
        gold:    { 400:'#ffd700', 500:'#e6c000' },
        'cyan-400': '#40c4ff',
      },
      animation: {
        'pulse-fast':       'pulse 0.72s cubic-bezier(.4,0,.6,1) infinite',
        'pulse-ring':       'pulseRing 1.4s ease-out infinite',
        'spin-slow':        'spin 6s linear infinite',
        'float':            'float 3.6s ease-in-out infinite',
        'shimmer':          'shimmer 3s linear infinite',
        'slide-up':         'slideUp .45s ease-out both',
        'slide-down':       'slideDown .35s ease-out both',
        'slide-left':       'slideLeft .4s ease-out both',
        'fade-in':          'fadeIn .4s ease-out both',
        'scale-in':         'scaleIn .35s ease-out both',
        'pop-in':           'popIn .45s cubic-bezier(.34,1.56,.64,1) both',
        'glow':             'glow 2.5s ease-in-out infinite',
        'correct-flash':    'correctFlash .6s ease-out',
        'wrong-shake':      'wrongShake .5s ease-out',
        'countdown-pop':    'countdownPop .55s cubic-bezier(.34,1.56,.64,1)',
        'streak-bounce':    'streakBounce .5s cubic-bezier(.34,1.56,.64,1)',
      },
      keyframes: {
        float:          { '0%,100%':{ transform:'translateY(0)' },       '50%':{ transform:'translateY(-14px)' } },
        shimmer:        { '0%':{ backgroundPosition:'-200% center' },    '100%':{ backgroundPosition:'200% center' } },
        slideUp:        { from:{ opacity:'0', transform:'translateY(30px)' },  to:{ opacity:'1', transform:'translateY(0)' } },
        slideDown:      { from:{ opacity:'0', transform:'translateY(-20px)' }, to:{ opacity:'1', transform:'translateY(0)' } },
        slideLeft:      { from:{ opacity:'0', transform:'translateX(30px)' },  to:{ opacity:'1', transform:'translateX(0)' } },
        fadeIn:         { from:{ opacity:'0' }, to:{ opacity:'1' } },
        scaleIn:        { from:{ opacity:'0', transform:'scale(0.86)' },  to:{ opacity:'1', transform:'scale(1)' } },
        popIn:          { '0%':{ opacity:'0', transform:'scale(0.5)' }, '70%':{ transform:'scale(1.08)' }, '100%':{ opacity:'1', transform:'scale(1)' } },
        glow:           { '0%,100%':{ boxShadow:'0 0 15px rgba(0,255,136,0.25)' }, '50%':{ boxShadow:'0 0 35px rgba(0,255,136,0.6)' } },
        pulseRing:      { '0%':{ boxShadow:'0 0 0 0 rgba(0,255,136,0.4)' }, '70%':{ boxShadow:'0 0 0 12px rgba(0,255,136,0)' }, '100%':{ boxShadow:'0 0 0 0 rgba(0,255,136,0)' } },
        correctFlash:   { '0%,100%':{ background:'transparent' }, '50%':{ background:'rgba(0,255,136,0.18)' } },
        wrongShake:     { '0%,100%':{ transform:'translateX(0)' }, '20%':{ transform:'translateX(-8px)' }, '40%':{ transform:'translateX(8px)' }, '60%':{ transform:'translateX(-5px)' }, '80%':{ transform:'translateX(5px)' } },
        countdownPop:   { '0%':{ transform:'scale(1.5)', opacity:'0' }, '40%':{ transform:'scale(0.95)', opacity:'1' }, '70%':{ transform:'scale(1.05)' }, '100%':{ transform:'scale(1)' } },
        streakBounce:   { '0%':{ transform:'scale(1)' }, '30%':{ transform:'scale(1.35)' }, '60%':{ transform:'scale(0.92)' }, '100%':{ transform:'scale(1)' } },
        gradientShift:  { '0%':{ backgroundPosition:'0% 50%' }, '50%':{ backgroundPosition:'100% 50%' }, '100%':{ backgroundPosition:'0% 50%' } },
      },
      backgroundImage: {
        'pitch-gradient': 'linear-gradient(135deg, #04080f 0%, #0d1a2e 50%, #04080f 100%)',
      },
    },
  },
  plugins: [],
};
